name: nopCommerce CI/CD Pipeline

on:
  # push:
  #   branches: [ main, develop ]
  # pull_request:
  #   branches: [ main ]
  # release:
  #   types: [published]
  workflow_dispatch:

env:
  DOTNET_VERSION: '9.0'
  PUBLISH_PATH: './published'
  SOLUTION_FILE: '*.sln'
  PUBLISH_DIRECTORY: 'published'
  ZIP_NAME: 'nopcommerce-package-${{ github.run_number }}.zip'

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore src/Presentation/Nop.Web/Nop.Web.csproj

    - name: Build solution
      run: dotnet build src/Presentation/Nop.Web/Nop.Web.csproj --configuration Release --no-restore

    - name: Run tests with coverage
      run: |
        dotnet test src/Tests/Nop.Tests/Nop.Tests.csproj \
          -c Release \
          --logger "trx;LogFileName=results.trx" \
          --results-directory TestResults \
          --diag:log.txt \
          --verbosity minimal

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: ./TestResults/**/*
        retention-days: 30
    

    - name: Publish Project
      run: |
        dotnet publish src/Presentation/Nop.Web/Nop.Web.csproj --configuration Release --output ${{ env.PUBLISH_DIRECTORY }} --no-build

    - name: Create zip package
      run: |
        cd ${{ env.PUBLISH_DIRECTORY }}
        zip -r "../${{ env.ZIP_NAME }}" ./*
        cd ..
    - name: Upload zip artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ZIP_NAME }}
        path: ${{ env.ZIP_NAME }}
    